### ISSUE TITLE
请问品牌,型号信息hook为何不生效？

### ISSUE THREAD

**Issue by xf005** [rk700/ChangePhoneInfo#1]
请问品牌，型号信息hook为何不生效？还是需要在java中重新hook？
static Prop props [] = {
    {"ro.serialno", "1234567890"},
    {"ro.product.brand", "foo"},
    {"ro.product.device", "bar"},
    {"ro.build.tags", "release-keys"},
    {"ro.product.model", "foo"},
    {"ro.product.manufacturer", "bar"}
};

**Comment by rk700** [comment]
如果是从android.os.Build去获取设备信息，那么就通过反射直接修改相应的静态字段。因为Build类在hook之前就已经被初始化完成了

示例：
https://github.com/rk700/ChangePhoneInfo/commit/6458b8e29e4b7b2453549686388dfff1579e28cd#diff-0e410134ca527c48f88b8aeb55c397a6R15
